package frc.team670.mustanglib.subsystems;

import edu.wpi.first.networktables.EntryListenerFlags;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.NetworkTableType;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.team670.mustanglib.constants.RobotConstantsBase;
import frc.team670.mustanglib.utils.MustangNotifications;

/**
 * Stores values off of NetworkTables for easy retrieval and gives them
 * Listeners to update the stored values as they are changed.
 * 
 * @author lakshbhambhani, katia, pallavi
 */
public class VisionSubsystemBase extends MustangSubsystemBase {

    private Solenoid cameraLEDs;

    private static final String VISION_TRIGGER_KEY = "vision-enabled";
    private static final String VISION_VALUES_KEY = "vision-values";

    private static final String VISION_MIN_HSV_KEY = "vision-minHSV";
    private static final String VISION_MAX_HSV_KEY = "vision-maxHSV";
    private static final String VISION_SHAPE_KEY = "vision-shape";

    private static final String VISION_HEALTH_KEY = "vision-health";

    private double angle;
    private double distance;

    /**
     * Used to create a basic Vision Subsystem object
     * @param minHSV array of minHSV values for vision system
     * @param maxHSV array of maxHSV values for vision system
     * @param shape the points of the shape the vision system is looking for
     * @param PCMModulePort the port PCM is connected to
     * @param visionLEDPCMPort the port vision leds are connected on the PCM
     */
    public VisionSubsystemBase(double[] minHSV, double[] maxHSV, double[] shape, int PCMModulePort, int visionLEDPCMPort) {
        cameraLEDs = new Solenoid(PCMModulePort, visionLEDPCMPort);
        SmartDashboard.putBoolean("LEDs on", false);
        
        SmartDashboard.putNumberArray(VISION_MIN_HSV_KEY, minHSV);
        SmartDashboard.putNumberArray(VISION_MAX_HSV_KEY, maxHSV);
        SmartDashboard.putNumberArray(VISION_SHAPE_KEY, shape);
    }

    /**
     * Used to trigger the vision system to run and get new values
     */
    private void triggerVision() {
        SmartDashboard.putBoolean(VISION_TRIGGER_KEY, true);
    }

    /**
     * Used to get the values generated by vision subsystem once vision code runs on pi using triggerVision
     */
    private void getLatestVisionData() {
        Double[] values = SmartDashboard.getNumberArray(VISION_VALUES_KEY, new Double[] {-1.0,-1.0});
        angle = values[0];
        distance = values[1];
    }

    /**
     * Used to clear last values present on the table
     */
    public void clearLastValues(){
        SmartDashboard.putNumberArray(VISION_VALUES_KEY, new Double[] {-1.0,-1.0});
    }

    /**
     * 
     * @return the horizontal angle between the camera-forward to the robot-target line
     */
    public double getAngleToTarget() {
        triggerVision();
        getLatestVisionData();
        return angle;
    }

    /**
     * 
     * @return distance, in inches, from the camera to the target
     */
    private double getDistanceToTargetInches() {
        triggerVision();
        getLatestVisionData();
        return distance;
    }

    /**
     * 
     * @return distance, in cm, from the camera to the target
     */
    public double getDistanceToTargetMeters() {
        return getDistanceToTargetInches() * 25.4;
    }

    /**
     * Used to turn on the bright green leds for vision so picture taken can detect green reflective target regions
     */
    public void turnOnLEDs() {
        cameraLEDs.set(true);
    }

    /**
     * Used to turn off the bright green leds for vision to save power and when not using vision
     */
    public void turnOffLEDs() {
        cameraLEDs.set(false);
    }

    /**
     * Used to test the leds for vision
     */
    public void testLEDS() {
        cameraLEDs.set(SmartDashboard.getBoolean("LEDs on", true));
    }

    @Override
    public HealthState checkHealth() {
        HealthState state;

        String visionHealth = SmartDashboard.getString(VISION_HEALTH_KEY, "RED");

        if (visionHealth == "RED") {
            state = HealthState.RED;
            MustangNotifications.reportError("RED Error: Vision System");
        } else if (visionHealth == "YELLOW") {
            state = HealthState.YELLOW;
            MustangNotifications.reportWarning("YELLOW Error: Vision System");
        } else {
            state = HealthState.GREEN;
        }
        return state;
    }

    @Override
    public void mustangPeriodic() { 

    }

}